  @extends('Layouts.clean')
  @section('childContent')
    @include('Layouts.partials.header')
      @yield('content')
    @hasSection('footerLinks')
      <footer>
        @yield('footerLinks')
      </footer>
    @endif
  @endsection
